n = 16
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_CHANNEL_ACTION,
    GET_CHANNEL_ID,
    GET_POLL_ACTION_OR_DELETE_CHANNEL,
    GET_POLL_TITLE,
    GET_POLL_PHOTO,
    GET_POLL_TEXT,
    GET_POLL_OPTIONS,
    CONFIRM_POLL,

    
) = range(0, n)